server:
  port: 80

spring:
  application:
    name: cloud-comsumer-order

#eureka-client配置
eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka # 入驻地址 (注意点：/eureka service端是默认带上,所以client端入驻地址需要带上)